# Site settings
name: Yongmin's Dev Lab
email: hapitd@naver.com
author: Yongmin
url: http://momobs.github.io
resume_site: http://momobs.github.io/resume
github: http://github.com/momobs
baseurl: ""
description: Clean Code!
meta_description: meta_desc
motto: Simple & Clean.
banner: banner

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: momobs

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

